language: node_js
node_js: 11
sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - xvfb

os:
  - linux

env:
global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

install:
  - yarn install --force


script:
  - node --version
  - npm --version
  - yarn install
  - yarn test
