language: node_js
node_js: 11
cache: npm
sudo: required
addons:
  apt:
    packages:
      - xvfb
  chrome: stable

os:
  - linux

env:
global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # Install all dependencies listed in your package.json file
  - yarn install --force

script:
  - echo "Tests"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run npm run test; else npm run test; fi
